##############################################################################
# @file  Directories.cmake
# @brief CMake variables of project directories.
#
# @note The file Directories.cmake is automatically generated by BASIS from
#       the template file Directories.cmake.in which is part of BASIS.
#
# @sa http://www.rad.upenn.edu/sbia/software/basis/standard/fhs/
#
# Copyright (c) 2011, 2012 University of Pennsylvania. All rights reserved.<br />
# See http://www.rad.upenn.edu/sbia/software/license.html or COPYING file.
#
# Contact: SBIA Group <sbia-software at uphs.upenn.edu>
##############################################################################

## @addtogroup BasisDirectories
#  @{


# ============================================================================
# script site packages directories
# ============================================================================

## @brief Default directory for Python site packages.
set (PYTHON_SITELIB "/gpfs/sbia/sbiasfw/external/python/epd/7.3.1/lib/python2.7/site-packages")
## @brief Default directory for Jython site packages.
set (JYTHON_SITELIB "/gpfs/sbia/sbiasfw/external/jython/centos5/2.5.1/Lib/site-packages")
## @brief Default directory for Perl site packages.
set (PERL_SITELIB "/usr/lib/perl5/site_perl/5.8.8")

# ============================================================================
# source tree
# ============================================================================

## @brief Absolute path of directory of project sources in source tree.
set (PROJECT_CODE_DIR "/sbia/home/bergman/MASS/MASS_1.1.0/src")
## @brief Absolute path of directory of BASIS project configuration in source tree.
set (PROJECT_CONFIG_DIR "/sbia/home/bergman/MASS/MASS_1.1.0/config")
## @brief Absolute path of directory of auxiliary data in source tree.
set (PROJECT_DATA_DIR "/sbia/home/bergman/MASS/MASS_1.1.0/data")
## @brief Absolute path of directory of documentation files in source tree.
set (PROJECT_DOC_DIR "/sbia/home/bergman/MASS/MASS_1.1.0/doc")
## @brief Absolute path of directory of example in source tree.
set (PROJECT_EXAMPLE_DIR "/sbia/home/bergman/MASS/MASS_1.1.0/example")
## @brief Absolute path of directory of public header files in source tree.
set (PROJECT_INCLUDE_DIR "/sbia/home/bergman/MASS/MASS_1.1.0/include")
## @brief Absolute path of directory of public scripted packages.
set (PROJECT_LIBRARY_DIR "/sbia/home/bergman/MASS/MASS_1.1.0/lib")
## @brief Absolute path of directory of project modules.
set (PROJECT_MODULES_DIR "/sbia/home/bergman/MASS/MASS_1.1.0/modules")
## @brief Absolute path of directory of testing tree in source tree.
set (PROJECT_TESTING_DIR "/sbia/home/bergman/MASS/MASS_1.1.0/test")

# ============================================================================
# testing tree
# ============================================================================

## @brief Absolute path of output directory for tests.
set (TESTING_OUTPUT_DIR "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos5/Testing/Temporary")
## @brief Absolute path of output directory for built test executables.
set (TESTING_RUNTIME_DIR "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos5/Testing/bin")
## @brief Absolute path of output directory for auxiliary executables used by tests.
set (TESTING_LIBEXEC_DIR "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos5/Testing/lib")
## @brief Absolute path of output directory for testing libraries.
set (TESTING_LIBRARY_DIR "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos5/Testing/lib")

## @brief Absolute path of output directory for Python modules used for testing.
set (TESTING_PYTHON_LIBRARY_DIR "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos5/Testing/lib/python")
## @brief Absolute path of output directory for Jython modules used for testing.
set (TESTING_JYTHON_LIBRARY_DIR "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos5/Testing/lib/jython")
## @brief Absolute path of output directory for Perl modules used for testing.
set (TESTING_PERL_LIBRARY_DIR "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos5/Testing/lib/perl")
## @brief Absolute path of output directory for MATLAB modules used for testing.
set (TESTING_MATLAB_LIBRARY_DIR "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos5/Testing/lib/matlab")
## @brief Absolute path of output directory for Bash modules used for testing.
set (TESTING_BASH_LIBRARY_DIR "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos5/Testing/lib/bash")

# ============================================================================
# build tree
# ============================================================================

## @brief Absolute path of output directory for main executables.
set (BINARY_RUNTIME_DIR "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos5/bin")
## @brief Absolute path of output directory for auxiliary executables.
set (BINARY_LIBEXEC_DIR "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos5/lib")
## @brief Absolute path of output directory for configured public header files.
set (BINARY_INCLUDE_DIR "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos5/include")
## @brief Absolute path of output directory for shared libraries and modules.
set (BINARY_LIBRARY_DIR "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos5/lib")
## @brief Absolute path of output directory for static and import libraries.
set (BINARY_ARCHIVE_DIR "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos5/lib")

## @brief Absolute path of output directory for Python modules.
set (BINARY_PYTHON_LIBRARY_DIR "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos5/lib/python")
## @brief Absolute path of output directory for Jython modules.
set (BINARY_JYTHON_LIBRARY_DIR "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos5/lib/jython")
## @brief Absolute path of output directory for Perl modules.
set (BINARY_PERL_LIBRARY_DIR "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos5/lib/perl")
## @brief Absolute path of output directory for MATLAB modules.
set (BINARY_MATLAB_LIBRARY_DIR "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos5/lib/matlab")
## @brief Absolute path of output directory for Bash modules.
set (BINARY_BASH_LIBRARY_DIR "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos5/lib/bash")

# ============================================================================
# install tree
# ============================================================================

## @brief Installation prefix, i.e., root directory of installation.
set (CMAKE_INSTALL_PREFIX "/sbia/sbiasfw/lab/mass/1.1.0")

## @brief Path of installation directory for CMake package configuration
#         files relative to @c CMAKE_INSTALL_PREFIX.
#
# Install configuration files of modules in subdirectories such that
# CMake does not find them by default. Their might be a case that
# someone is using two projects where the one project is named just
# the same as the module of the other project. The configuration file
# of the module is anyway supposed to be included by the package
# configuration file if this module is requested by the COMPONENTS
# argument to the find_package() command.
set (INSTALL_CONFIG_DIR "lib/cmake/mass")
## @brief Path of installation directory for runtime executables and shared
#         libraries on Windows relative to @c CMAKE_INSTALL_PREFIX.
set (INSTALL_RUNTIME_DIR "bin")
## @brief Path of installation directory for auxiliary executables
#         relative to @c CMAKE_INSTALL_PREFIX.
set (INSTALL_LIBEXEC_DIR "lib")
## @brief Path of installation directory for public header files
#         relative to @c CMAKE_INSTALL_PREFIX.
#
# @note If the @c INCLUDE_PREFIX specifies subdirectories, these will be
#       created underneath this directory during the installation.
set (INSTALL_INCLUDE_DIR "include")
## @brief Path of installation directory for shared libraries on Unix-based
#         systems and module libraries relative to @c CMAKE_INSTALL_PREFIX.
set (INSTALL_LIBRARY_DIR "lib")
## @brief Path of installation directory for static and import libraries
#         relative to @c CMAKE_INSTALL_PREFIX.
set (INSTALL_ARCHIVE_DIR "lib")

# Similar to the public header files of C/C++ libraries, the modules written
# in Python or Perl are installed with fixed relative directories which
# correspond to the packages these modules belong to:
#
# For example, the Python module <vendor>.<pkg>.<module> is installed
# in the subdirectory <vendor>/<pkg>/<module>/ relative to the
# installation path for public Python modules, i.e., INSTALL_PYTHON_LIBRARY_DIR.
# External users of this module will add the INSTALL_PYTHON_LIBRARY_DIR
# to the search path for Python modules and import the module, for example, as
# follows:
#
# from <vendor>.<pkg> import <module>

## @brief Path of installation directory of private Python modules relative to @c CMAKE_INSTALL_PREFIX.
set (INSTALL_PYTHON_LIBRARY_DIR "lib/python")
## @brief Path of installation directory of private Jython modules relative to @c CMAKE_INSTALL_PREFIX.
set (INSTALL_JYTHON_LIBRARY_DIR "lib/jython")
## @brief Path of installation directory of private Perl modules relative to @c CMAKE_INSTALL_PREFIX.
set (INSTALL_PERL_LIBRARY_DIR "lib/perl")
## @brief Path of installation directory of private MATLAB M-files relative to @c CMAKE_INSTALL_PREFIX.
set (INSTALL_MATLAB_LIBRARY_DIR "lib/matlab")
## @brief Path of installation directory of private Bash modules relative to @c CMAKE_INSTALL_PREFIX.
set (INSTALL_BASH_LIBRARY_DIR "lib/bash")

## @brief Path of installation directory of public Python modules relative to @c CMAKE_INSTALL_PREFIX.
set (INSTALL_PYTHON_SITE_DIR "lib/python")
## @brief Path of installation directory of public Jython modules relative to @c CMAKE_INSTALL_PREFIX.
set (INSTALL_JYTHON_SITE_DIR "lib/jython")
## @brief Path of installation directory of public Perl modules relative to @c CMAKE_INSTALL_PREFIX.
set (INSTALL_PERL_SITE_DIR "lib/perl")
## @brief Path of installation directory of public MATLAB M-files relative to @c CMAKE_INSTALL_PREFIX.
set (INSTALL_MATLAB_SITE_DIR "lib/matlab")
## @brief Path of installation directory of public Bash modules relative to @c CMAKE_INSTALL_PREFIX.
set (INSTALL_BASH_SITE_DIR "lib/bash")

## @brief Path of installation directory for shared files relative to @c CMAKE_INSTALL_PREFIX.
set (INSTALL_SHARE_DIR "share")
## @brief Path of installation directory for shared data files relative to @c CMAKE_INSTALL_PREFIX.
set (INSTALL_DATA_DIR "share/data")
## @brief Path of installation directory for documentation files relative to @c CMAKE_INSTALL_PREFIX.
set (INSTALL_DOC_DIR "doc")
## @brief Path of installation directory for example files relative to @c CMAKE_INSTALL_PREFIX.
set (INSTALL_EXAMPLE_DIR "share/example")
## @brief Path of installation directory for man pages relative to @c CMAKE_INSTALL_PREFIX.
set (INSTALL_MAN_DIR "man")
## @brief Path of Texinfo files relative to @c CMAKE_INSTALL_PREFIX.
set (INSTALL_TEXINFO_DIR "info")

# ============================================================================
# top-level references
# ============================================================================

## @brief Absolute path of root directory of source tree of top-level project.
set (BASIS_PROJECT_SOURCE_DIR "/sbia/home/bergman/MASS/MASS_1.1.0")
## @brief Absolute path of root directory of build tree of top-level project.
set (BASIS_PROJECT_BINARY_DIR "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos5")


## @}
# end of Doxygen group
