##############################################################################
# @file  ScriptConfig.cmake
# @brief Default script configuration.
#
# @note The file ScriptConfig.cmake is automatically generated by BASIS from
#       the template file ScriptConfig.cmake.in which is part the
#       MASS package.
#
#
# Use the function basis_set_script_path() to set a file or directory path
# relative to the script file's location.
#
# Example:
# @code
# basis_set_script_path (SOME_DIR "")
# basis_set_script_path (RUNTIME_DIR "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/bin" "bin")
# @endcode
#
# See documentation of basis_set_script_path() function for more details.
#
# @sa http://www.cbica.upenn.edu/sbia/software/basis/standard/scripttargets.html#script-configuration
#
# Copyright (c) 2011-2014 University of Pennsylvania. All rights reserved.<br />
# See http://www.cbica.upenn.edu/sbia/software/license.html or COPYING file.
#
# Contact: SBIA Group <sbia-software at uphs.upenn.edu>
#
# @ingroup BasisScriptConfig
##############################################################################

## @addtogroup BasisScriptConfig
# @{
	# Define different paths for DATA_DIR and LIBRARY_DIR during build and installation process
	if (BUILD_INSTALL_SCRIPT)
		set (DATA_DIR "/sbia/sbiasfw/lab/mass/centos6/1.1.0/share/data")
		set (LIBRARY_DIR "/sbia/sbiasfw/lab/mass/centos6/1.1.0/lib")
		set (LIBEXEC_DIR "/sbia/sbiasfw/lab/mass/centos6/1.1.0/lib")
		set (BASH_LIBRARY_DIR "/sbia/sbiasfw/lab/mass/centos6/1.1.0/lib/bash/mass")
	else ()
		set (DATA_DIR "/sbia/home/bergman/MASS/MASS_1.1.0/data")
		set (LIBRARY_DIR "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/lib")
		set (LIBEXEC_DIR "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/lib")
		set (BASH_LIBRARY_DIR "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/lib/bash/mass")
	endif ()

## @}
# end of Doxygen group - keep at end of file
