# CMake generated Testfile for 
# Source directory: /sbia/home/bergman/MASS/MASS_1.1.0/test
# Build directory: /sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/test
# 
# This file includes the relevent testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(mass_fillholes_test "/sbiasfw/lab/basis/2.1.2/centos6/lib/testdriver" "--intensity-tolerance" "0.01" "--compare" "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/Testing/Temporary/mass_fillholes_test/TestCase1_444_byte_brainmask_holes_filled.nii.gz" "/sbia/home/bergman/MASS/MASS_1.1.0/test/baseline/TestCase1_444_byte_brainmask_holes_filled.nii.gz" "--" "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/lib/mass-fillHoles" "-in" "/sbia/home/bergman/MASS/MASS_1.1.0/test/baseline/TestCase1_444_byte_brainmask_holes.nii.gz" "-dest" "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/Testing/Temporary/mass_fillholes_test/" "-v")
SET_TESTS_PROPERTIES(mass_fillholes_test PROPERTIES  FAIL_REGULAR_EXPRESSION "(\\[ *PASSED *\\]|Ran) 0 tests|No tests were found!!!" LABELS "mass" WORKING_DIRECTORY "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/Testing/Temporary/mass_fillholes_test")
ADD_TEST(mass_morpho-dilate_test "/sbiasfw/lab/basis/2.1.2/centos6/lib/testdriver" "--intensity-tolerance" "0.01" "--compare" "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/Testing/Temporary/mass_morpho-dilate_test/TestCase1_444_byte_brainmask_dil2mm.nii.gz" "/sbia/home/bergman/MASS/MASS_1.1.0/test/baseline/TestCase1_444_byte_brainmask_dil2mm.nii.gz" "--" "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/lib/mass-morpho" "-in" "/sbia/home/bergman/MASS/MASS_1.1.0/test/baseline/TestCase1_444_byte_brainmask.nii.gz" "-dilate" "-dest" "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/Testing/Temporary/mass_morpho-dilate_test/" "-kernel" "2" "-v")
SET_TESTS_PROPERTIES(mass_morpho-dilate_test PROPERTIES  FAIL_REGULAR_EXPRESSION "(\\[ *PASSED *\\]|Ran) 0 tests|No tests were found!!!" LABELS "mass" WORKING_DIRECTORY "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/Testing/Temporary/mass_morpho-dilate_test")
ADD_TEST(mass_morpho-erode_test "/sbiasfw/lab/basis/2.1.2/centos6/lib/testdriver" "--intensity-tolerance" "0.01" "--compare" "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/Testing/Temporary/mass_morpho-erode_test/TestCase1_444_byte_brainmask_ero2mm.nii.gz" "/sbia/home/bergman/MASS/MASS_1.1.0/test/baseline/TestCase1_444_byte_brainmask_ero2mm.nii.gz" "--" "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/lib/mass-morpho" "-in" "/sbia/home/bergman/MASS/MASS_1.1.0/test/baseline/TestCase1_444_byte_brainmask.nii.gz" "-erode" "-dest" "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/Testing/Temporary/mass_morpho-erode_test/" "-kernel" "2" "-v")
SET_TESTS_PROPERTIES(mass_morpho-erode_test PROPERTIES  FAIL_REGULAR_EXPRESSION "(\\[ *PASSED *\\]|Ran) 0 tests|No tests were found!!!" LABELS "mass" WORKING_DIRECTORY "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/Testing/Temporary/mass_morpho-erode_test")
ADD_TEST(mass_chooseTemplates_test "/sbiasfw/lab/basis/2.1.2/centos6/lib/testdriver" "--diff" "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/Testing/Temporary/mass_chooseTemplates_test/ChosenTemplates.txt" "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/Testing/Temporary/mass_chooseTemplates_test/ChosenTemplates_baseline.txt" "--" "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/bin/mass-chooseTemplates" "-list" "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/Testing/Temporary/mass_chooseTemplates_test/FileList.txt" "-clust" "1" "-dest" "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/Testing/Temporary/mass_chooseTemplates_test/" "-pref" "ChosenTemplates.txt" "-MT" "12" "-v")
SET_TESTS_PROPERTIES(mass_chooseTemplates_test PROPERTIES  FAIL_REGULAR_EXPRESSION "(\\[ *PASSED *\\]|Ran) 0 tests|No tests were found!!!" LABELS "mass" WORKING_DIRECTORY "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/Testing/Temporary/mass_chooseTemplates_test")
ADD_TEST(mass_registrations_test "/sbiasfw/lab/basis/2.1.2/centos6/lib/testdriver" "--intensity-tolerance" "0.01" "--compare" "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/Testing/Temporary/mass_registrations_test/TestCase1_444_byte-Template1_mask_InSpace.nii.gz" "/sbia/home/bergman/MASS/MASS_1.1.0/test/baseline/TestCase1_444_byte-Template1_mask_InSpace.nii.gz" "--compare" "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/Testing/Temporary/mass_registrations_test/TestCase1_444_byte-Template1_affine_warp_jacobian.nii.gz" "/sbia/home/bergman/MASS/MASS_1.1.0/test/baseline/TestCase1_444_byte-Template1_affine_warp_jacobian.nii.gz" "--" "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/lib/mass-registrations" "-in" "/sbia/home/bergman/MASS/MASS_1.1.0/test/baseline/TestCase1_444_byte.nii.gz" "-ref" "/sbia/home/bergman/MASS/MASS_1.1.0/data/Templates/WithCerebellum/Template1.nii.gz" "-str" "/sbia/home/bergman/MASS/MASS_1.1.0/data/Templates/WithCerebellum/Template1_str_cbq.nii.gz" "-dest" "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/Testing/Temporary/mass_registrations_test/" "-v" "1")
SET_TESTS_PROPERTIES(mass_registrations_test PROPERTIES  FAIL_REGULAR_EXPRESSION "(\\[ *PASSED *\\]|Ran) 0 tests|No tests were found!!!" LABELS "mass" WORKING_DIRECTORY "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/Testing/Temporary/mass_registrations_test")
ADD_TEST(mass_skullstripping_test "/sbiasfw/lab/basis/2.1.2/centos6/lib/testdriver" "--intensity-tolerance" "0.01" "--compare" "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/Testing/Temporary/mass_skullstripping_test/TestCase1_444_byte_brain.nii.gz" "/sbia/home/bergman/MASS/MASS_1.1.0/test/baseline/TestCase1_444_byte_brain.nii.gz" "--compare" "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/Testing/Temporary/mass_skullstripping_test/TestCase1_444_byte_brainmask.nii.gz" "/sbia/home/bergman/MASS/MASS_1.1.0/test/baseline/TestCase1_444_byte_brainmask.nii.gz" "--compare" "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/Testing/Temporary/mass_skullstripping_test/TestCase1_444_byte_brain_JacRank.nii.gz" "/sbia/home/bergman/MASS/MASS_1.1.0/test/baseline/TestCase1_444_byte_brain_JacRank.nii.gz" "--" "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/lib/mass-skullstripping" "-in" "/sbia/home/bergman/MASS/MASS_1.1.0/test/baseline/TestCase1_444_byte.nii.gz" "-dest" "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/Testing/Temporary/mass_skullstripping_test/" "-mask" "TestCase1_444_byte_brainmask" "-cbq" "TestCase1_444_byte_brain" "-regs" "3" "-int" "1" "-jacRank" "1" "-v" "1")
SET_TESTS_PROPERTIES(mass_skullstripping_test PROPERTIES  FAIL_REGULAR_EXPRESSION "(\\[ *PASSED *\\]|Ran) 0 tests|No tests were found!!!" LABELS "mass" WORKING_DIRECTORY "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/Testing/Temporary/mass_skullstripping_test")
ADD_TEST(mass_thresholdJacobian_test "/sbiasfw/lab/basis/2.1.2/centos6/lib/testdriver" "--intensity-tolerance" "0.01" "--compare" "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/Testing/Temporary/mass_thresholdJacobian_test/TestCase1_444_byte_mask.nii.gz" "/sbia/home/bergman/MASS/MASS_1.1.0/test/baseline/TestCase1_444_byte_mask.nii.gz" "--" "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/bin/mass-thresholdJacobian" "-in" "/sbia/home/bergman/MASS/MASS_1.1.0/test/baseline/TestCase1_444_byte.nii.gz" "-jacRank" "/sbia/home/bergman/MASS/MASS_1.1.0/test/baseline/TestCase1_444_byte_brain_JacRank.nii.gz" "-dest" "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/Testing/Temporary/mass_thresholdJacobian_test/" "-perThresh" "70" "-v")
SET_TESTS_PROPERTIES(mass_thresholdJacobian_test PROPERTIES  FAIL_REGULAR_EXPRESSION "(\\[ *PASSED *\\]|Ran) 0 tests|No tests were found!!!" LABELS "mass" WORKING_DIRECTORY "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/Testing/Temporary/mass_thresholdJacobian_test")
ADD_TEST(mass_system_test "/sbiasfw/lab/basis/2.1.2/centos6/lib/testdriver" "--intensity-tolerance" "0.01" "--compare" "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/Testing/Temporary/mass_system_test/TestCase1_444_byte_brain.nii.gz" "/sbia/home/bergman/MASS/MASS_1.1.0/test/baseline/TestCase1_444_byte_brain.nii.gz" "--compare" "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/Testing/Temporary/mass_system_test/TestCase1_444_byte_brainmask.nii.gz" "/sbia/home/bergman/MASS/MASS_1.1.0/test/baseline/TestCase1_444_byte_brainmask.nii.gz" "--compare" "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/Testing/Temporary/mass_system_test/TestCase1_444_byte_brain_JacRank.nii.gz" "/sbia/home/bergman/MASS/MASS_1.1.0/test/baseline/TestCase1_444_byte_brain_JacRank.nii.gz" "--" "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/bin/mass" "-in" "/sbia/home/bergman/MASS/MASS_1.1.0/test/baseline/TestCase1_444_byte.nii.gz" "-dest" "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/Testing/Temporary/mass_system_test/" "-regs" "3" "-NOQ" "-MT" "12" "-log" "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/Testing/Temporary/mass_system_test/" "-delay" "1" "-int" "1" "-v")
SET_TESTS_PROPERTIES(mass_system_test PROPERTIES  FAIL_REGULAR_EXPRESSION "(\\[ *PASSED *\\]|Ran) 0 tests|No tests were found!!!" LABELS "mass" WORKING_DIRECTORY "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/Testing/Temporary/mass_system_test")
ADD_TEST(mass_scheduler_test "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/bin/mass" "-in" "/sbia/home/bergman/MASS/MASS_1.1.0/test/baseline/TestCase1_444_byte.nii.gz" "-dest" "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/Testing/Temporary/mass_scheduler_test/" "-regs" "3" "-log" "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/Testing/Temporary/mass_scheduler_test/" "-delay" "1" "-v")
SET_TESTS_PROPERTIES(mass_scheduler_test PROPERTIES  FAIL_REGULAR_EXPRESSION "(\\[ *PASSED *\\]|Ran) 0 tests|No tests were found!!!" LABELS "mass" WORKING_DIRECTORY "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/Testing/Temporary/mass_scheduler_test")
