/**
 * @file  basis.cxx
 * @brief BASIS utilities of MASS project of MASS package.
 *
 * @note The basis.cxx module was automatically generated by BASIS from the
 *       template file basis.cxx.in which is part of the BASIS installation.
 *
 * Copyright (c) 2011, 2012 University of Pennsylvania. All rights reserved.<br />
 * See http://www.rad.upenn.edu/sbia/software/license.html or COPYING file.
 *
 * Contact: SBIA Group <sbia-software at uphs.upenn.edu>
 */

#include <map>

#include <mass//basis.h>


// acceptable in .cxx file
using namespace std;
using namespace basis;


namespace mass {


// ===========================================================================
// constants
// ===========================================================================

// ---------------------------------------------------------------------------
// project attributes
const char* PROJECT = "MASS";
const char* VERSION = "1.1.0";
const char* RELEASE = "v1.1";

const unsigned int VERSION_MAJOR = 1;
const unsigned int VERSION_MINOR = 1;
const unsigned int VERSION_PATCH = 0;

const char* COPYRIGHT = "2014 University of Pennsylvania";
const char* LICENSE   = "See COPYING file.";
const char* CONTACT   = "SBIA Group <sbia-software at uphs.upenn.edu>";

// ===========================================================================
// local helper functions
// ===========================================================================

/**
 * @brief Determine if this is the built or the installed executable.
 *
 * @returns Whether the executable was executed from within the build tree.
 */
static inline bool executing_in_build_tree()
{
    // get executable path relative to top directory of build tree
    string rel_path = os::path::relpath(
            // directory of this executable
            os::exedir(),
            // The following path is the absolute path of the top directory of the build
            // tree in which the software was built. It can be used to determine whether
            // an executable is executing from within the build tree rather than an
            // installation. Given that we tend to build software in a directory with the
            // prefix "-build", but never choose such directory for the installation prefix,
            // a check whether or not the location of the executable file is inside this
            // build tree is enough to know whether or not it is executed from within the
            // build tree or an installation.
            os::path::realpath("/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6"));
    // return whether executable directory is inside the build tree or not
    return !(rel_path == "" || rel_path == "." ||
            (rel_path.substr(0, 2) == ".." && (rel_path.size() == 2 || rel_path[2] == '/')));
}

// ===========================================================================
// class: ExecutableTargetInfo (declaration)
// ===========================================================================

// The definition of the class methods can be found at the end of this file.

/**
 * @brief Provides information about executable build targets.
 *
 * @sa IExecutableTargetInfo
 */
class ExecutableTargetInfo : public basis::util::IExecutableTargetInfo
{
    // -----------------------------------------------------------------------
    // typedefs
private:

    typedef std::map <std::string, std::string> MapType;
    typedef MapType::const_iterator             MapIterator;

    // -----------------------------------------------------------------------
    // construction / destruction
private:

    /**
     * @brief Constructor.
     *
     * Initializes the data members. The initialization code is in particular
     * generated by BASIS during the configuration of the build system.
     */
    ExecutableTargetInfo();

    /// @brief Destructor.
    ~ExecutableTargetInfo() {}

public:

    /**
     * @brief Get static instance of this module.
     *
     * @attention This method is not thread-safe!
     *
     * @return Static instance of this class.
     */
    static const ExecutableTargetInfo* instance();

    // -----------------------------------------------------------------------
    // public interface
public:

    std::string targetuid(const std::string& target) const;
    bool istarget(const std::string& target) const;
    std::string basename(const std::string& target) const;
    std::string dirname(const std::string& target) const;

    // -----------------------------------------------------------------------
    // unsupported methods
private:

    /**
     * @brief Copy constructor.
     *
     * @note Intentionally not implemented.
     */
    ExecutableTargetInfo(const ExecutableTargetInfo&);

    /**
     * @brief Assignment operator.
     *
     * @note Intentionally not implemented.
     */
    void operator=(const ExecutableTargetInfo&);

    // -----------------------------------------------------------------------
    // members
private:

    /// Maps build target names to executable file names.
    MapType _exec_names;
    /// Maps build target names to output directories in build tree.
    MapType _build_dirs;
    /// Maps build target names to installation directories relative to
    /// installation prefix as returned by GetInstallationPrefix().
    MapType _install_dirs;

}; // class ExecutableTargetInfo

// ===========================================================================
// package directories
// ===========================================================================

/**
 * @brief Get absolute path of installation directory.
 *
 * This function returns the absolute path of the installation prefix path.
 * If the installation was not moved after a "make install", the returned
 * directory corresponds to the value of the INSTALL_PREFIX CMake variable
 * as specified during the build of the executable file. Note, however,
 * that even when the installation tree was moved after the configuration
 * and build of the software, the correct path is returned as long as the
 * relative directory structure of the installation tree is maintained.
 * This is because the path is determined relative to the directory of the
 * executable itself, knowning in which path this executable is located
 * relative to the INSTALL_PREFIX.
 *
 * @note If the executable is executed from within the build tree, the
 *       returned path will not be correct. Therefore, only use this
 *       function when executing_in_build_tree() returns false. Otherwise,
 *       the configured absolute paths which are valid for the build tree
 *       have to be used. Note that the build tree is not supposed to be
 *       relocatable in any case as it is only a temporary directory tree
 *       and CMake requires it to be not moved anywhere else.
 *
 * @returns Absolute path of top directory of installation tree.
 */
static string install_prefix()
{
#ifdef LIBEXEC
    return os::path::join(os::exedir(), "..");
#else
    return os::path::join(os::exedir(), "..");
#endif
}

// ---------------------------------------------------------------------------
string bindir()
{
    if (executing_in_build_tree()) {
        return "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/bin";
    } else {
        return os::path::join(install_prefix(), "bin");
    }
}

// ---------------------------------------------------------------------------
string libexecdir()
{
    if (executing_in_build_tree()) {
        return "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/lib";
    } else {
        return os::path::join(install_prefix(), "lib");
    }
}

// ---------------------------------------------------------------------------
string libdir()
{
    if (executing_in_build_tree()) {
        return "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/lib";
    } else {
        return os::path::join(install_prefix(), "lib");
    }
}

// ---------------------------------------------------------------------------
string datadir()
{
    if (executing_in_build_tree()) {
        return "/sbia/home/bergman/MASS/MASS_1.1.0/data";
    } else {
        return os::path::join(install_prefix(), "share/data");
    }
}

// ===========================================================================
// executable information
// ===========================================================================

// ---------------------------------------------------------------------------
void print_contact(const char* contact)
{
    basis::util::print_contact(contact != NULL ? contact : CONTACT);
}

// ---------------------------------------------------------------------------
void print_version(const char* name, const char* version, const char* project, const char* copyright, const char* license)
{
    basis::util::print_version(name,
                               version   != NULL ? version   : RELEASE,
                               project   != NULL ? project   : PROJECT,
                               copyright != NULL ? copyright : COPYRIGHT,
                               license   != NULL ? license   : LICENSE);
}

// ---------------------------------------------------------------------------
string targetuid(const string& name)
{
    return basis::util::targetuid(name, ExecutableTargetInfo::instance());
}

// ---------------------------------------------------------------------------
bool istarget(const string& name)
{
    return basis::util::istarget(name, ExecutableTargetInfo::instance());
}

// ---------------------------------------------------------------------------
string exepath(const string& name)
{
    return basis::util::exepath(name, ExecutableTargetInfo::instance());
}

// ---------------------------------------------------------------------------
string exename(const std::string& name)
{
    return basis::util::exename(name, ExecutableTargetInfo::instance());
}

// ---------------------------------------------------------------------------
string exedir(const std::string& name)
{
    return basis::util::exedir(name, ExecutableTargetInfo::instance());
}

// ===========================================================================
// command execution
// ===========================================================================

// ---------------------------------------------------------------------------
int execute(const string& cmd, bool quiet, ostream* out,
            bool allow_fail, int verbose, bool simulate)
{
    return basis::util::execute(cmd, quiet, out, allow_fail, verbose, simulate,
                                ExecutableTargetInfo::instance());
}

// ---------------------------------------------------------------------------
int execute(vector<string> args, bool quiet, ostream* out,
            bool allow_fail, int verbose, bool simulate)
{
    return basis::util::execute(args, quiet, out, allow_fail, verbose, simulate,
                                ExecutableTargetInfo::instance());
}

// ===========================================================================
// class: ExecutableTargetInfo (definition)
// ===========================================================================

// ---------------------------------------------------------------------------
const ExecutableTargetInfo* ExecutableTargetInfo::instance()
{
    static ExecutableTargetInfo instance;
    return &instance;
}

// ---------------------------------------------------------------------------
string ExecutableTargetInfo::targetuid(const string& target) const
{
    // empty(, invalid) target name remains unchanged
    if (target.empty()) return "";
    // in case of a leading namespace separator, do not modify target name
    if (target[0] == '.') return target;
    // project namespace
    string prefix = string("mass");
    // try prepending namespace or parts of it until target is known
    for (;;) {
        if (_exec_names.find(prefix + "." + target) != _exec_names.end()) {
            return prefix + "." + target;
        }
        string::size_type pos = prefix.rfind('.');
        if (pos == string::npos) break;
        prefix = prefix.substr(0, pos);
    }
    // otherwise, return target name unchanged
    return target;
}

// ---------------------------------------------------------------------------
bool ExecutableTargetInfo::istarget(const string& target) const
{
    if (target.empty()) return false;
    string uid;
    if (target[0] == '.') uid = target.substr(1);
    else uid = targetuid(target);
    return _exec_names.find(uid) != _exec_names.end();
}

// ---------------------------------------------------------------------------
string ExecutableTargetInfo::basename(const string& target) const
{
    if (target.empty()) return "";
    string uid;
    if (target[0] == '.') uid = target.substr(1);
    else uid = targetuid(target);
    MapIterator it = _exec_names.find(uid);
    if (it == _exec_names.end ()) return "";
    return it->second;
}

// ---------------------------------------------------------------------------
string ExecutableTargetInfo::dirname(const string& target) const
{
    if (target.empty()) return "";
    string uid;
    if (target[0] == '.') uid = target.substr(1);
    else uid = targetuid(target);
    if (executing_in_build_tree()) {
        MapIterator it = _build_dirs.find(uid);
        if (it == _build_dirs.end()) return "";
        #if defined CMAKE_INTDIR
            // this subdirectory is used by CMake generators for IDEs such as Visual Studio
            return os::path::join(it->second, CMAKE_INTDIR);
        #else
            return it->second;
        #endif
    } else {
        MapIterator it = _install_dirs.find(uid);
        if (it == _install_dirs.end()) return "";
        return os::path::join(install_prefix(), it->second);
    }
}

// ---------------------------------------------------------------------------
ExecutableTargetInfo::ExecutableTargetInfo()
{
    // the following code was automatically generated by the BASIS
    // CMake function basis_configure_ExecutableTargetInfo()

    // mass
    _exec_names  ["mass.mass"]                            = "mass";
    _build_dirs  ["mass.mass"]                            = "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/bin";
    _install_dirs["mass.mass"]                            = "/sbia/sbiasfw/lab/mass/centos6/1.1.0/bin";

    // mass-chooseTemplates
    _exec_names  ["mass.mass-chooseTemplates"]            = "mass-chooseTemplates";
    _build_dirs  ["mass.mass-chooseTemplates"]            = "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/bin";
    _install_dirs["mass.mass-chooseTemplates"]            = "/sbia/sbiasfw/lab/mass/centos6/1.1.0/bin";

    // mass-thresholdJacobian
    _exec_names  ["mass.mass-thresholdJacobian"]          = "mass-thresholdJacobian";
    _build_dirs  ["mass.mass-thresholdJacobian"]          = "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/bin";
    _install_dirs["mass.mass-thresholdJacobian"]          = "/sbia/sbiasfw/lab/mass/centos6/1.1.0/bin";

    // mass-fillHoles
    _exec_names  ["mass.mass-fillHoles"]                  = "mass-fillHoles";
    _build_dirs  ["mass.mass-fillHoles"]                  = "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/lib";
    _install_dirs["mass.mass-fillHoles"]                  = "/sbia/sbiasfw/lab/mass/centos6/1.1.0/lib";

    // mass-morpho
    _exec_names  ["mass.mass-morpho"]                     = "mass-morpho";
    _build_dirs  ["mass.mass-morpho"]                     = "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/lib";
    _install_dirs["mass.mass-morpho"]                     = "/sbia/sbiasfw/lab/mass/centos6/1.1.0/lib";

    // mass-registrations
    _exec_names  ["mass.mass-registrations"]              = "mass-registrations";
    _build_dirs  ["mass.mass-registrations"]              = "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/lib";
    _install_dirs["mass.mass-registrations"]              = "/sbia/sbiasfw/lab/mass/centos6/1.1.0/lib";

    // mass-skullstripping
    _exec_names  ["mass.mass-skullstripping"]             = "mass-skullstripping";
    _build_dirs  ["mass.mass-skullstripping"]             = "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/lib";
    _install_dirs["mass.mass-skullstripping"]             = "/sbia/sbiasfw/lab/mass/centos6/1.1.0/lib";

    // mass-choosetemplate
    _exec_names  ["mass.mass-choosetemplate"]             = "mass-choosetemplate";
    _build_dirs  ["mass.mass-choosetemplate"]             = "/sbia/home/bergman/MASS/MASS_1.1.0/build-centos6/lib";
    _install_dirs["mass.mass-choosetemplate"]             = "/sbia/sbiasfw/lab/mass/centos6/1.1.0/lib";

    // basis.testdriver
    _exec_names  ["basis.testdriver"]                     = "testdriver";
    _build_dirs  ["basis.testdriver"]                     = "/sbiasfw/lab/basis/2.1.2/centos6/lib";
    _install_dirs["basis.testdriver"]                     = "/sbiasfw/lab/basis/2.1.2/centos6/lib";

    // basis.basisproject
    _exec_names  ["basis.basisproject"]                   = "basisproject";
    _build_dirs  ["basis.basisproject"]                   = "/sbiasfw/lab/basis/2.1.2/centos6/bin";
    _install_dirs["basis.basisproject"]                   = "/sbiasfw/lab/basis/2.1.2/centos6/bin";

    // basis.doxyfilter
    _exec_names  ["basis.doxyfilter"]                     = "doxyfilter";
    _build_dirs  ["basis.doxyfilter"]                     = "/sbiasfw/lab/basis/2.1.2/centos6/lib";
    _install_dirs["basis.doxyfilter"]                     = "/sbiasfw/lab/basis/2.1.2/centos6/lib";

    // basis.doxyfilter-perl
    _exec_names  ["basis.doxyfilter-perl"]                = "doxyfilter-perl";
    _build_dirs  ["basis.doxyfilter-perl"]                = "/sbiasfw/lab/basis/2.1.2/centos6/lib";
    _install_dirs["basis.doxyfilter-perl"]                = "/sbiasfw/lab/basis/2.1.2/centos6/lib";

    // basis.basistest-svn
    _exec_names  ["basis.basistest-svn"]                  = "basistest-svn";
    _build_dirs  ["basis.basistest-svn"]                  = "/sbiasfw/lab/basis/2.1.2/centos6/lib";
    _install_dirs["basis.basistest-svn"]                  = "/sbiasfw/lab/basis/2.1.2/centos6/lib";

    // basis.basistest-slave
    _exec_names  ["basis.basistest-slave"]                = "basistest-slave";
    _build_dirs  ["basis.basistest-slave"]                = "/sbiasfw/lab/basis/2.1.2/centos6/lib";
    _install_dirs["basis.basistest-slave"]                = "/sbiasfw/lab/basis/2.1.2/centos6/lib";

    // basis.basistest-master
    _exec_names  ["basis.basistest-master"]               = "basistest-master";
    _build_dirs  ["basis.basistest-master"]               = "/sbiasfw/lab/basis/2.1.2/centos6/lib";
    _install_dirs["basis.basistest-master"]               = "/sbiasfw/lab/basis/2.1.2/centos6/lib";

    // basis.basistest-cron
    _exec_names  ["basis.basistest-cron"]                 = "basistest-cron";
    _build_dirs  ["basis.basistest-cron"]                 = "/sbiasfw/lab/basis/2.1.2/centos6/lib";
    _install_dirs["basis.basistest-cron"]                 = "/sbiasfw/lab/basis/2.1.2/centos6/lib";

    // basis.basistest
    _exec_names  ["basis.basistest"]                      = "basistest";
    _build_dirs  ["basis.basistest"]                      = "/sbiasfw/lab/basis/2.1.2/centos6/bin";
    _install_dirs["basis.basistest"]                      = "/sbiasfw/lab/basis/2.1.2/centos6/bin";

    // dramms.CheckTwoImages
    _exec_names  ["dramms.CheckTwoImages"]                = "CheckTwoImages";
    _build_dirs  ["dramms.CheckTwoImages"]                = "/sbia/sbiasfw/lab/dramms/centos6/1.4.1/lib";
    _install_dirs["dramms.CheckTwoImages"]                = "/sbia/sbiasfw/lab/dramms/centos6/1.4.1/lib";

    // dramms.GenerateGaborListFile
    _exec_names  ["dramms.GenerateGaborListFile"]         = "GenerateGaborListFile";
    _build_dirs  ["dramms.GenerateGaborListFile"]         = "/sbia/sbiasfw/lab/dramms/centos6/1.4.1/lib";
    _install_dirs["dramms.GenerateGaborListFile"]         = "/sbia/sbiasfw/lab/dramms/centos6/1.4.1/lib";

    // dramms.GenerateImageListFile
    _exec_names  ["dramms.GenerateImageListFile"]         = "GenerateImageListFile";
    _build_dirs  ["dramms.GenerateImageListFile"]         = "/sbia/sbiasfw/lab/dramms/centos6/1.4.1/lib";
    _install_dirs["dramms.GenerateImageListFile"]         = "/sbia/sbiasfw/lab/dramms/centos6/1.4.1/lib";

    // dramms.CalculateImageSimilarity
    _exec_names  ["dramms.CalculateImageSimilarity"]      = "CalculateImageSimilarity";
    _build_dirs  ["dramms.CalculateImageSimilarity"]      = "/sbia/sbiasfw/lab/dramms/centos6/1.4.1/lib";
    _install_dirs["dramms.CalculateImageSimilarity"]      = "/sbia/sbiasfw/lab/dramms/centos6/1.4.1/lib";

    // dramms.CombineFeatureLists
    _exec_names  ["dramms.CombineFeatureLists"]           = "CombineFeatureLists";
    _build_dirs  ["dramms.CombineFeatureLists"]           = "/sbia/sbiasfw/lab/dramms/centos6/1.4.1/lib";
    _install_dirs["dramms.CombineFeatureLists"]           = "/sbia/sbiasfw/lab/dramms/centos6/1.4.1/lib";

    // dramms.CombineTransforms
    _exec_names  ["dramms.CombineTransforms"]             = "dramms-combine";
    _build_dirs  ["dramms.CombineTransforms"]             = "/sbia/sbiasfw/lab/dramms/centos6/1.4.1/bin";
    _install_dirs["dramms.CombineTransforms"]             = "/sbia/sbiasfw/lab/dramms/centos6/1.4.1/bin";

    // dramms.CalculateGaborTextures
    _exec_names  ["dramms.CalculateGaborTextures"]        = "CalculateGaborTextures";
    _build_dirs  ["dramms.CalculateGaborTextures"]        = "/sbia/sbiasfw/lab/dramms/centos6/1.4.1/lib";
    _install_dirs["dramms.CalculateGaborTextures"]        = "/sbia/sbiasfw/lab/dramms/centos6/1.4.1/lib";

    // dramms.MatchHistograms
    _exec_names  ["dramms.MatchHistograms"]               = "MatchHistograms";
    _build_dirs  ["dramms.MatchHistograms"]               = "/sbia/sbiasfw/lab/dramms/centos6/1.4.1/lib";
    _install_dirs["dramms.MatchHistograms"]               = "/sbia/sbiasfw/lab/dramms/centos6/1.4.1/lib";

    // dramms.ApplyTransform
    _exec_names  ["dramms.ApplyTransform"]                = "dramms-warp";
    _build_dirs  ["dramms.ApplyTransform"]                = "/sbia/sbiasfw/lab/dramms/centos6/1.4.1/bin";
    _install_dirs["dramms.ApplyTransform"]                = "/sbia/sbiasfw/lab/dramms/centos6/1.4.1/bin";

    // dramms.CalculateJacobianMap
    _exec_names  ["dramms.CalculateJacobianMap"]          = "dramms-jacobian";
    _build_dirs  ["dramms.CalculateJacobianMap"]          = "/sbia/sbiasfw/lab/dramms/centos6/1.4.1/bin";
    _install_dirs["dramms.CalculateJacobianMap"]          = "/sbia/sbiasfw/lab/dramms/centos6/1.4.1/bin";

    // dramms.CalculateRavensMaps
    _exec_names  ["dramms.CalculateRavensMaps"]           = "dramms-ravens";
    _build_dirs  ["dramms.CalculateRavensMaps"]           = "/sbia/sbiasfw/lab/dramms/centos6/1.4.1/bin";
    _install_dirs["dramms.CalculateRavensMaps"]           = "/sbia/sbiasfw/lab/dramms/centos6/1.4.1/bin";

    // dramms.ImageOperation
    _exec_names  ["dramms.ImageOperation"]                = "dramms-imgop";
    _build_dirs  ["dramms.ImageOperation"]                = "/sbia/sbiasfw/lab/dramms/centos6/1.4.1/bin";
    _install_dirs["dramms.ImageOperation"]                = "/sbia/sbiasfw/lab/dramms/centos6/1.4.1/bin";

    // dramms.TransformOperation
    _exec_names  ["dramms.TransformOperation"]            = "dramms-defop";
    _build_dirs  ["dramms.TransformOperation"]            = "/sbia/sbiasfw/lab/dramms/centos6/1.4.1/bin";
    _install_dirs["dramms.TransformOperation"]            = "/sbia/sbiasfw/lab/dramms/centos6/1.4.1/bin";

    // dramms.ConvertDeformation
    _exec_names  ["dramms.ConvertDeformation"]            = "dramms-convert";
    _build_dirs  ["dramms.ConvertDeformation"]            = "/sbia/sbiasfw/lab/dramms/centos6/1.4.1/bin";
    _install_dirs["dramms.ConvertDeformation"]            = "/sbia/sbiasfw/lab/dramms/centos6/1.4.1/bin";

    // dramms.ConvertImage
    _exec_names  ["dramms.ConvertImage"]                  = "ConvertImage";
    _build_dirs  ["dramms.ConvertImage"]                  = "/sbia/sbiasfw/lab/dramms/centos6/1.4.1/lib";
    _install_dirs["dramms.ConvertImage"]                  = "/sbia/sbiasfw/lab/dramms/centos6/1.4.1/lib";

    // dramms.Deform2D
    _exec_names  ["dramms.Deform2D"]                      = "Deform2D";
    _build_dirs  ["dramms.Deform2D"]                      = "/sbia/sbiasfw/lab/dramms/centos6/1.4.1/lib";
    _install_dirs["dramms.Deform2D"]                      = "/sbia/sbiasfw/lab/dramms/centos6/1.4.1/lib";

    // dramms.Deform3D
    _exec_names  ["dramms.Deform3D"]                      = "Deform3D";
    _build_dirs  ["dramms.Deform3D"]                      = "/sbia/sbiasfw/lab/dramms/centos6/1.4.1/lib";
    _install_dirs["dramms.Deform3D"]                      = "/sbia/sbiasfw/lab/dramms/centos6/1.4.1/lib";

    // dramms.dramms
    _exec_names  ["dramms.dramms"]                        = "dramms";
    _build_dirs  ["dramms.dramms"]                        = "/sbia/sbiasfw/lab/dramms/centos6/1.4.1/bin";
    _install_dirs["dramms.dramms"]                        = "/sbia/sbiasfw/lab/dramms/centos6/1.4.1/bin";
}


} // end of namespaces
